.\"	$Id$
.\"
.\" Copyright (c) 2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining
.\" a copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so, subject to
.\" the following conditions:
.\" 
.\" The above copyright notice and this permission notice shall be
.\" included in all copies or substantial portions of the Software.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
.\" EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
.\" NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
.\" BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
.\" ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
.\" CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt DIFF 3
.Os
.Sh NAME
.Nm diff
.Nd generate arbitrary sequence diffs
.Sh LIBRARY
.Lb libdiff
.Sh SYNOPSIS
.In diff.h
.Ft int
.Fo diff
.Fa "struct diff *p"
.Fa "onp_sequence_t *p1"
.Fa "size_t sz1"
.Fa "onp_sequence_t *p2"
.Fa "size_t sz2"
.Fc
.Sh DESCRIPTION
The
.Fn diff
function generates the shortest edit script, least common subsequence,
and edit distance between
.Fa p1
of
.Fa sz1
elements and
.Fa p2
of
.Fa sz2
elements.
On success, it fills the
.Fa p->ses
with the shortest common subsequence of length
.Fa p->sessz .
.\" .Sh SEE ALSO
.\" .Sh AUTHORS
